AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple authentication API using SAM

Parameters:
  SenderEmail:
    Type: String
    Description: Email address to use as sender for SES
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    ConstraintDescription: Must be a valid email address
    
Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-jwt-secret
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: secret
        PasswordLength: 64
        ExcludeCharacters: '"@/\\'

  # Lambda Functions
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          JWT_SECRET_NAME: !Ref JWTSecret
          SENDER_EMAIL: !Ref SenderEmail
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Ref JWTSecret
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/*
      Events:
        Register:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post
        Activate:
          Type: Api
          Properties:
            Path: /auth/activate
            Method: get
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
        GetUser:
          Type: Api
          Properties:
            Path: /auth/user
            Method: get
        ResetPassword:
          Type: Api
          Properties:
            Path: /auth/user
            Method: put
        DeleteUser:
          Type: Api
          Properties:
            Path: /auth/user
            Method: delete
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/